### ISSUE TITLE
Compiled test suites don't build with Swift 6.4: no such module 'ImarkRender'

### ISSUE THREAD

**Issue by mekh** [migsilva89/imark#34]
### What happened

With Swift 6.4, the compiled suites in CONTRIBUTING and `release.sh` — `test-editor` and `test-undo` — stop at the first import:

```
Sources/Imark/ContentViewController.swift:2:8: error: no such module 'ImarkRender'
```

SwiftPM in Swift 6.4 builds with Swift Build by default (`--build-system native` is deprecated). Its products go to `.build/out/Products/Debug`, with `ImarkRender.swiftmodule` beside them and no `Modules/` folder, so `-I "$TEST_BIN/Modules"` points at nothing. With `--build-system native` the old layout (`.build/arm64-apple-macosx/debug/Modules`) comes back and the commands work.

`./release.sh` stops at "the undo tests failed" for the same reason.

Expected: the suites build with either build system.

A fix is in the PR that follows: pass `-I "$TEST_BIN"` as well as `-I "$TEST_BIN/Modules"`. Checked with both build systems.

### Imark version

`main` at e080fb5 (0.6.2)

### macOS version

26.6.2, with Swift 6.4 (swiftlang-6.4.0.34.1)
